### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by dwieeb** [wcatron/ionic-cloud-sdk-php#1]
Let's talk dependencies! 

We're going to definitely need a JWT library and a HTTP library.

What are your thoughts on these?
- JWT: https://github.com/firebase/php-jwt
- HTTP: https://github.com/guzzle/guzzle

Any other dependencies you can think of, @wcatron?

**Comment by wcatron** [comment]
JWT was my first thought. Guzzle is what AWS uses and if it's good enough for Amazon.

- PHPUnit: https://github.com/sebastianbergmann/phpunit

I've got JWT and PHP already setup. Just pushed my initial code which has JWT.

**Comment by dwieeb** [comment]
Yes, definitely PHPUnit. 

I wish I could comment specific lines of files.

**Comment by dwieeb** [comment]
Yes, definitely PHPUnit. 

I wish I could comment specific lines of files.

**Comment by wcatron** [comment]
Well how about collaborator status?

**Comment by wcatron** [comment]
Well how about collaborator status?
