### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by wcatron** [wcatron/ionic-cloud-sdk-php#2]
Decide on a documentation system.

- Sphinx: http://www.sphinx-doc.org/en/stable/
- PHPDocs: https://www.phpdoc.org/docs/latest/index.html

I've used PHPDocs but they can get really messy inside the classes. I've seen a lot of major projects using Sphinx and Restructured Text (guzzle, swift). @dwieeb I couldn't find your docs in a repo to see what you guys use. I'm up for whatever.

**Comment by dwieeb** [comment]
We basically use jekyll and a bunch of custom stuff. I've used Sphinx and it's great but I'm sure we don't quite need something like that yet. PHPDocs is a simple input/output. Let's give it a try :+1:

**Comment by wcatron** [comment]
Okay, I did get the impression Sphinx was for large scale projects. We can stick to PHPDocs.

**Comment by wcatron** [comment]
PHPDocs are setup and can be created following the documentation guide. Obviously individual guides and documentation need to be created but we're setup.
